language: node_js
sudo: required
services:
- docker
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
- sudo apt-get -o Dpkg::Options::="--force-confnew" -y update
- sudo apt-get -o Dpkg::Options::="--force-confnew" -y install docker-engine
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "XKjf0ZpP8tTgNEjS/IUfsTEXPz7Ott6b3MLsjtFsgn9RzJCYRmW6D5PJY9oaiPgHHEev9TTg1pjaayvw76b556+Ig1kY49fA5yKnyf0TGuCApWJTRHbsphRjZ1oOouF47+TnZdq2ALpJEsCqGu7yaGpZdAheUB4Dh7Fq3jkCKQnQLKio94BBh/FwJCVWeRXNu+dTX4z+/iuBatL/KmeSvw1PhpmsGf/zPBEOhLz5aypysuuRh5zlb3ZA8qBZB/OuBl4KyJKKHlaBhhk08qIfWi186wbnZpKfajUXydfhZ3HI16PsJXFP1nX1sZsOEzDJk2VD9UqUi3s1hK9iaddLFPQJIWnvtUtZ+UPdsQ5CdZ9oVbTmaNoriHccNWE4xdlcVznRDdKbab6fIA7pSj7OZramr7HSVQozH3CcZjlsPu8coFYnUXmlA9BLoowWHBn+O7obrny482/LyJqWhG70YcBRvqdp3K1DOBp40fwTYl1TJTP2AKdl6PcYby11BaKnya9elIS1ti7m/fRl/sXb0qlata5kP0E/A0+B5Hl81BOJU44Iyk7o+jEcxxxyvJkwJisTcOO4JpqGa4C0vRphP/MYNAJQBeEhNhdgOnCr21ZiJbvdyaU9/BpY7haaBESlNe5beV6UTyxWoJFEcFh+pMGGTdToe+tx8SRbPTFpneM="
